FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    mpich

# Download and compile OSU benchmarks
RUN wget http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.7.tar.gz \
    && tar -xzf osu-micro-benchmarks-5.7.tar.gz \
    && cd osu-micro-benchmarks-5.7 \
    && ./configure CC=mpicc CXX=mpicxx \
    && make \
    && make install

# Set the working directory
WORKDIR /osu-micro-benchmarks-5.7/mpi

CMD ["mpirun", "-np", "2", "./pt2pt/osu_latency"]
